[package]
name = "hello-actix"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "~0.6"
env_logger = "~0.9"
futures-util = "0.3"
log = "~0.4"
mime = "0.3"
mime_guess = "2.0"
